spring:
  #MySql ˝æ›ø‚≈‰÷√
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url:jdbc:mysql://localhost:3306/dongzhebk?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 19990930